In [1]:
#Instalaciones básicas
import pandas as pd
import sys
sys.path.append("..")
import openpyxl 
from src import soporte as sp

In [2]:
#Importamos el Excel con datos de los clientes
customer_data = pd.ExcelFile("C:/Users/cargo/Documents/EDA_banco/data/customer-details.xlsx", engine="openpyxl")

In [3]:
#Comprobamos cuantas hojas contiene
print("Hojas disponibles:", customer_data.sheet_names)

Hojas disponibles: ['2012', '2013', '2014']

In [4]:
# Cargamos todas las hojas en un solo DataFrame
sheets = [customer_data.parse(sheet) for sheet in customer_data.sheet_names]
customer_df = pd.concat(sheets, ignore_index=True)

In [5]:
df = customer_data.parse(sheet_name="2012")  # Reemplaza "Sheet1" por el nombre correcto
print(df.head())  # Mostrar primeras filas

   Unnamed: 0  Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
0           0  161770        1         0  2012-04-04                 29
1           1   85477        1         1  2012-12-30                  7
2           2  147233        1         1  2012-02-02                  5
3           3  121393        1         2  2012-12-21                 29
4           4   63164        1         2  2012-06-20                 20

                                     ID
0  089b39d8-e4d0-461b-87d4-814d71e0e079
1  e9d37224-cb6f-4942-98d7-46672963d097
2  3f9f49b5-e410-4948-bf6e-f9244f04918b
3  9991fafb-4447-451a-8be2-b0df6098d13e
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [6]:
# Cargamos todas las hojas y unirlas en un solo DataFrame
sheets = [customer_data.parse(sheet) for sheet in customer_data.sheet_names]
df_combined = pd.concat(sheets, ignore_index=True)

print(df_combined.head())

   Unnamed: 0  Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
0           0  161770        1         0  2012-04-04                 29
1           1   85477        1         1  2012-12-30                  7
2           2  147233        1         1  2012-02-02                  5
3           3  121393        1         2  2012-12-21                 29
4           4   63164        1         2  2012-06-20                 20

                                     ID
0  089b39d8-e4d0-461b-87d4-814d71e0e079
1  e9d37224-cb6f-4942-98d7-46672963d097
2  3f9f49b5-e410-4948-bf6e-f9244f04918b
3  9991fafb-4447-451a-8be2-b0df6098d13e
4  eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [7]:
# Información del DataFrame
print(df_combined.info())

# Ver valores nulos
print(df_combined.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.3+ MB
None
Unnamed: 0           0
Income               0
Kidhome              0
Teenhome             0
Dt_Customer          0
NumWebVisitsMonth    0
ID                   0
dtype: int64

In [8]:
df_combined.dtypes

Unnamed: 0                    int64
Income                        int64
Kidhome                       int64
Teenhome                      int64
Dt_Customer          datetime64[ns]
NumWebVisitsMonth             int64
ID                           object
dtype: object

In [9]:
sp.eda_preliminar(df_combined)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
36966,7886,6427,0,0,2014-10-30,24,1552af0e-33c1-47d5-a6bb-3b60440d535e
33898,4818,56163,2,2,2014-05-30,21,5d3dd8ab-ebe7-49c6-ab05-15ba72005192
5525,5525,20998,2,2,2012-05-09,17,8aa0982f-390f-4c43-a0e7-6fc9f213ca1c
2494,2494,115438,0,1,2012-05-11,10,bd911f70-0496-44f5-8015-e908106e6fe3
40393,11313,87591,1,2,2014-08-23,29,729a2ed3-9314-44e4-a6aa-adc0c1a085fb

-----------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
dtypes: datetime64[ns](1), int64(5), object(1)
memory usage: 2.3+ MB

None

-----------------
NULOS

Unnamed: 0           0.0
Income               0.0
Kidhome              0.0
Teenhome             0.0
Dt_Customer          0.0
NumWebVisitsMonth    0.0
ID                   0.0
dtype: float64

-----------------
DUPLICADOS
0
-----------------
VALUE COUNTS
ID
9727bc06-c11a-461a-a5bb-3d210467cc2a    1
089b39d8-e4d0-461b-87d4-814d71e0e079    1
5006b75e-18bb-46e9-ae1a-89f7eb79cc8a    1
e554d2ad-6c83-4603-93d4-fc596b807eff    1
3959015a-9713-4877-9a43-740e34c29eaf    1
                                       ..
5e3483e5-236d-437d-8351-541f9d09b9dd    1
d63ede72-0b6d-45b1-8872-385ac6897f65    1
eca60b76-70b6-4077-80ba-bc52e8ebb0eb    1
9991fafb-4447-451a-8be2-b0df6098d13e    1
3f9f49b5-e410-4948-bf6e-f9244f04918b    1
Name: count, Length: 43170, dtype: int64
----------------------------

In [10]:
#Borramos columna Unnamed:0
df_combined.drop(columns="Unnamed: 0", inplace=True)

In [11]:
df_combined.head().style.set_properties(**{'text-align': 'center'})

In [12]:
for col in df_combined.select_dtypes(include='O').columns:
    print(df_combined[col].value_counts())
    print('----------------------------')

ID
9727bc06-c11a-461a-a5bb-3d210467cc2a    1
089b39d8-e4d0-461b-87d4-814d71e0e079    1
5006b75e-18bb-46e9-ae1a-89f7eb79cc8a    1
e554d2ad-6c83-4603-93d4-fc596b807eff    1
3959015a-9713-4877-9a43-740e34c29eaf    1
                                       ..
5e3483e5-236d-437d-8351-541f9d09b9dd    1
d63ede72-0b6d-45b1-8872-385ac6897f65    1
eca60b76-70b6-4077-80ba-bc52e8ebb0eb    1
9991fafb-4447-451a-8be2-b0df6098d13e    1
3f9f49b5-e410-4948-bf6e-f9244f04918b    1
Name: count, Length: 43170, dtype: int64
----------------------------

In [13]:
print(df_combined)

       Income  Kidhome  Teenhome Dt_Customer  NumWebVisitsMonth  \
0      161770        1         0  2012-04-04                 29
1       85477        1         1  2012-12-30                  7
2      147233        1         1  2012-02-02                  5
3      121393        1         2  2012-12-21                 29
4       63164        1         2  2012-06-20                 20
...       ...      ...       ...         ...                ...
43165  156980        1         2  2014-05-17                  7
43166  139820        0         0  2014-09-29                  1
43167   78470        2         2  2014-10-28                 12
43168  144218        0         1  2014-07-01                  9
43169  115155        0         2  2014-12-25                  7

                                         ID
0      089b39d8-e4d0-461b-87d4-814d71e0e079
1      e9d37224-cb6f-4942-98d7-46672963d097
2      3f9f49b5-e410-4948-bf6e-f9244f04918b
3      9991fafb-4447-451a-8be2-b0df6098d13e
4      eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...                                     ...
43165  5f432048-d515-4bb5-9c94-62db451f88d4
43166  993bbbd6-4dbc-4a40-a408-f91f8462bee6
43167  d6271666-319d-42c8-a741-cb22bf2c2093
43168  f67fbfa8-6573-414d-a805-b26a2f1b1ceb
43169  9727bc06-c11a-461a-a5bb-3d210467cc2a

[43170 rows x 6 columns]

In [14]:
# Aplicar la función a cada nombre de columna
df_combined.columns = [sp.convert_column_name(col) for col in df_combined.columns]

In [15]:
print(df_combined)

       income  kidhome  teenhome dt_customer  num_web_visits_month  \
0      161770        1         0  2012-04-04                    29
1       85477        1         1  2012-12-30                     7
2      147233        1         1  2012-02-02                     5
3      121393        1         2  2012-12-21                    29
4       63164        1         2  2012-06-20                    20
...       ...      ...       ...         ...                   ...
43165  156980        1         2  2014-05-17                     7
43166  139820        0         0  2014-09-29                     1
43167   78470        2         2  2014-10-28                    12
43168  144218        0         1  2014-07-01                     9
43169  115155        0         2  2014-12-25                     7

                                        i_d
0      089b39d8-e4d0-461b-87d4-814d71e0e079
1      e9d37224-cb6f-4942-98d7-46672963d097
2      3f9f49b5-e410-4948-bf6e-f9244f04918b
3      9991fafb-4447-451a-8be2-b0df6098d13e
4      eca60b76-70b6-4077-80ba-bc52e8ebb0eb
...                                     ...
43165  5f432048-d515-4bb5-9c94-62db451f88d4
43166  993bbbd6-4dbc-4a40-a408-f91f8462bee6
43167  d6271666-319d-42c8-a741-cb22bf2c2093
43168  f67fbfa8-6573-414d-a805-b26a2f1b1ceb
43169  9727bc06-c11a-461a-a5bb-3d210467cc2a

[43170 rows x 6 columns]

In [16]:
#Abrimos el archivo limpio
bank_data = pd.read_csv("../data/data_a_analizar.csv", parse_dates=['date'])

In [17]:
print(bank_data.columns)

Index(['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact',
       'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'nr.employed', 'y', 'date', 'id_',
       'age_iterative', 'euribor3m_iterative'],
      dtype='object')

In [18]:
# Unir datasets en base al ID del cliente
merged_data = pd.merge(bank_data, df_combined, left_on="id_", right_on="i_d", how="left")

In [19]:
merged_data.to_csv('../data/datos_unidos.csv', index=False, date_format='%Y-%m-%d')

In [20]:
sp.eda_preliminar(merged_data)

,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,nr.employed,y,date,id_,age_iterative,euribor3m_iterative,income,kidhome,teenhome,dt_customer,num_web_visits_month,i_d
9924,technician,married,university.degree,no,no,no,telephone,136,2,999,0,nonexistent,1.4,94.465,-41.8,5228.1,no,2017-06-19,24240749-0346-4c36-98b2-d8aa6c7dd30c,59.0,4.958000,45712,1,0,2012-09-04,13,24240749-0346-4c36-98b2-d8aa6c7dd30c
24947,services,married,high.school,no,no,no,cellular,51,1,999,1,failure,-0.1,93.200,-42.0,5195.8,no,2019-03-20,bd706fa8-e6c8-40d3-8b5a-55768e9043b2,40.0,4.153000,135051,0,0,2013-11-09,3,bd706fa8-e6c8-40d3-8b5a-55768e9043b2
15463,services,single,high.school,no,yes,no,cellular,37,4,999,0,nonexistent,1.4,93.918,-42.7,5228.1,no,2015-01-03,6d10b882-84a5-4dbf-a89b-b5f283ec798d,26.0,3.374581,69640,1,0,2012-07-08,15,6d10b882-84a5-4dbf-a89b-b5f283ec798d
37422,technician,married,university.degree,no,no,no,cellular,224,3,999,0,nonexistent,-2.9,92.201,-31.4,5076.2,no,2015-08-14,85f08f20-3ca4-4842-9b29-e4638f1350b5,35.0,0.869000,149685,1,1,2014-07-18,8,85f08f20-3ca4-4842-9b29-e4638f1350b5
3571,admin,married,high.school,no,yes,yes,telephone,196,3,999,0,nonexistent,1.1,93.994,-36.4,5191.0,no,2016-10-08,9a0b82c5-c701-4b0c-a455-b7a1c93f9312,35.0,4.859000,129275,0,2,2012-09-08,4,9a0b82c5-c701-4b0c-a455-b7a1c93f9312

-----------------
INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   job                   43000 non-null  object
 1   marital               43000 non-null  object
 2   education             43000 non-null  object
 3   default               43000 non-null  object
 4   housing               43000 non-null  object
 5   loan                  43000 non-null  object
 6   contact               43000 non-null  object
 7   duration              43000 non-null  int64
 8   campaign              43000 non-null  int64
 9   pdays                 43000 non-null  int64
 10  previous              43000 non-null  int64
 11  poutcome              43000 non-null  object
 12  emp.var.rate          43000 non-null  float64
 13  cons.price.idx        43000 non-null  float64
 14  cons.conf.idx         43000 non-null  float64
 15  nr.employed           43000 non-null  float64
 16  y                     43000 non-null  object
 17  date                  43000 non-null  datetime64[ns]
 18  id_                   43000 non-null  object
 19  age_iterative         43000 non-null  float64
 20  euribor3m_iterative   43000 non-null  float64
 21  income                43000 non-null  int64
 22  kidhome               43000 non-null  int64
 23  teenhome              43000 non-null  int64
 24  dt_customer           43000 non-null  datetime64[ns]
 25  num_web_visits_month  43000 non-null  int64
 26  i_d                   43000 non-null  object
dtypes: datetime64[ns](2), float64(6), int64(8), object(11)
memory usage: 8.9+ MB

None

-----------------
NULOS

job                     0.0
marital                 0.0
education               0.0
default                 0.0
housing                 0.0
loan                    0.0
contact                 0.0
duration                0.0
campaign                0.0
pdays                   0.0
previous                0.0
poutcome                0.0
emp.var.rate            0.0
cons.price.idx          0.0
cons.conf.idx           0.0
nr.employed             0.0
y                       0.0
date                    0.0
id_                     0.0
age_iterative           0.0
euribor3m_iterative     0.0
income                  0.0
kidhome                 0.0
teenhome                0.0
dt_customer             0.0
num_web_visits_month    0.0
i_d                     0.0
dtype: float64

-----------------
DUPLICADOS
0
-----------------
VALUE COUNTS
job
admin            10873
blue-collar       9654
technician        7026
services          4162
management        3050
retired           1790
entrepreneur      1522
self-employed     1489
housemaid         1123
unemployed        1063
student            903
unknown            345
Name: count, dtype: int64
----------------------------
marital
married     25999
single      12105
divorced     4811
unknown        85
Name: count, dtype: int64
----------------------------
education
basic                  13051
university.degree      12722
high.school             9925
professional.course     5477
unknown                 1807
illiterate                18
Name: count, dtype: int64
----------------------------
default
no     42997
yes        3
Name: count, dtype: int64
----------------------------
housing
yes        22498
no         19476
unknown     1026
Name: count, dtype: int64
----------------------------
loan
no     36468
yes     6532
Name: count, dtype: int64
----------------------------
contact
cellular     27396
telephone    15604
Name: count, dtype: int64
----------------------------
poutcome
nonexistent    37103
failure         4461
success         1436
Name: count, dtype: int64
----------------------------
y
no     38156
yes     4844
Name: count, dtype: int64
----------------------------
id_
993bbbd6-4dbc-4a40-a408-f91f8462bee6    1
089b39d8-e4d0-461b-87d4-814d71e0e079    1
e9d37224-cb6f-4942-98d7-46672963d097    1
3f9f49b5-e410-4948-bf6e-f9244f04918b    1
9991fafb-4447-451a-8be2-b0df6098d13e    1
                                       ..
66a752e2-b2f1-440c-9a8f-cc3b10d74dd0    1
ca5c0d7a-8bbd-42b3-8351-1074c5be011a    1
8d700df5-0c33-4517-8cf8-92e1c92c9c12    1
ea6b7d04-9271-4c0a-a01f-07795d164aba    1
87b79988-2be5-419d-88f4-56655852c565    1
Name: count, Length: 43000, dtype: int64
----------------------------
i_d
993bbbd6-4dbc-4a40-a408-f91f8462bee6    1
089b39d8-e4d0-461b-87d4-814d71e0e079    1
e9d37224-cb6f-4942-98d7-46672963d097    1
3f9f49b5-e410-4948-bf6e-f9244f04918b    1
9991fafb-4447-451a-8be2-b0df6098d13e    1
                                       ..
66a752e2-b2f1-440c-9a8f-cc3b10d74dd0    1
ca5c0d7a-8bbd-42b3-8351-1074c5be011a    1
8d700df5-0c33-4517-8cf8-92e1c92c9c12    1
ea6b7d04-9271-4c0a-a01f-07795d164aba    1
87b79988-2be5-419d-88f4-56655852c565    1
Name: count, Length: 43000, dtype: int64
----------------------------

In [21]:
#Eliminamos la columna duplicada "id_"
merged_data = merged_data.drop(columns='id_')

In [22]:
#Generamos una columna para realizar analisis por grupos de edades
merged_data['age_group'] = merged_data['age_iterative'].apply(sp.age_group)

In [23]:
merged_data.to_csv('../data/data_para_KPIS.csv', index=False, date_format='%Y-%m-%d')